Changing the credentials

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -11,13 +11,13 @@ on:
         description: "Base URL for the Airflow API endpoint in MCP Venue Dev (i.e. https://abcdef12345.execute-api.us-west-2.amazonaws.com/dev/sps/api/v1)"
         type: string
       MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT:
-        description: "Base URL for the OGC API endpoint in MCP Venue Dev (i.e. http://abc.def.ghi:port-number)"
+        description: "Base URL for the OGC API endpoint in MCP Venue Dev (i.e. https://abcdef12345.execute-api.us-west-2.amazonaws.com/dev/ogc/api)"
         type: string
-      MCP_VENUE_TEST_AIRFLOW_ENDPOINT:
-         description: "Base URL for the Airflow endpoint in MCP Venue Test (i.e. http://abc.def.ghi:port-number)"
+      MCP_VENUE_TEST_AIRFLOW_API_ENDPOINT:
+         description: "Base URL for the Airflow API endpoint in MCP Venue Test (i.e. https://abcdef12345.execute-api.us-west-2.amazonaws.com/test/sps/api/v1)"
          type: string
       MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT:
-        description: "Base URL for the OGC endpoint in MCP Venue Test (i.e. http://abc.def.ghi:port-number)"
+        description: "Base URL for the OGC endpoint in MCP Venue Test (i.e. https://abcdef12345.execute-api.us-west-2.amazonaws.com/test/ogc/api)"
         type: string
       # TODO: add MCP_VENUE_OPS inputs
 jobs:
@@ -37,9 +37,9 @@ jobs:
       id: mcp_venue_dev_integration_tests_with_airflow_api
       continue-on-error: true
       env:
-        MCP_VENUE_DEV_UNITY_USERNAME: ${{ secrets.MCP_VENUE_DEV_UNITY_USERNAME }}
-        MCP_VENUE_DEV_UNITY_PASSWORD: ${{ secrets.MCP_VENUE_DEV_UNITY_PASSWORD }}
-        MCP_VENUE_DEV_UNITY_CLIENTID: ${{ secrets.MCP_VENUE_DEV_UNITY_CLIENTID }}
+        UNITY_USERNAME: ${{ secrets.MCP_VENUE_DEV_UNITY_USERNAME }}
+        UNITY_PASSWORD: ${{ secrets.MCP_VENUE_DEV_UNITY_PASSWORD }}
+        UNITY_CLIENTID: ${{ secrets.MCP_VENUE_DEV_UNITY_CLIENTID }}
       run: |
         pytest -vv -s --gherkin-terminal-reporter \
         unity-test/system/integration/step_defs/test_cwl_workflows_with_airflow_api.py  \
@@ -57,40 +57,40 @@ jobs:
           exit 1
         fi
 
-#  Dev-Venue-OGC-API:
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#    - name: Checkout
-#      uses: actions/checkout@v4
-#
-#    - name: Setup
-#      uses: ./.github/actions/setup-action
-#      continue-on-error: false
-#
-#    - name: MCP Venue Dev - Integration tests with OGC API
-#      id: mcp_venue_dev_integration_tests_with_ogc_api
-#      continue-on-error: true
-#      env:
-#        AIRFLOW_WEBSERVER_PASSWORD: ${{ secrets.MCP_VENUE_DEV_AIRFLOW_WEBSERVER_PASSWORD }}
-#        UNITY_USER: ${{ secrets.UNITY_USER }}
-#        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
-#      run: |
-#        pytest -vv -s --gherkin-terminal-reporter \
-#        unity-test/system/integration/step_defs/test_cwl_workflows_with_ogc_api.py  \
-#        --venue="dev" \
-#        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_ENDPOINT }} \
-#        --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT || vars.MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT }}
-#
-#    - name: Check Tests Results
-#      if: always()
-#      run: |
-#        tests_status=${{ steps.mcp_venue_dev_integration_tests_with_ogc_api.outcome }}
-#        echo "Tests Status: $tests_status"
-#        if [ "$tests_status" != "success" ]; then
-#          echo "Integration Tests with OGC API on MCP Venue Dev failed."
-#          exit 1
-#        fi
+  Dev-Venue-OGC-API:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+
+    - name: Setup
+      uses: ./.github/actions/setup-action
+      continue-on-error: false
+
+    - name: MCP Venue Dev - Integration tests with OGC API
+      id: mcp_venue_dev_integration_tests_with_ogc_api
+      continue-on-error: true
+      env:
+        UNITY_USERNAME: ${{ secrets.MCP_VENUE_DEV_UNITY_USERNAME }}
+        UNITY_PASSWORD: ${{ secrets.MCP_VENUE_DEV_UNITY_PASSWORD }}
+        UNITY_CLIENTID: ${{ secrets.MCP_VENUE_DEV_UNITY_CLIENTID }}
+      run: |
+        pytest -vv -s --gherkin-terminal-reporter \
+        unity-test/system/integration/step_defs/test_cwl_workflows_with_ogc_api.py  \
+        --venue="dev" \
+        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_API_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_API_ENDPOINT }} \
+        --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT || vars.MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT }}
+
+    - name: Check Tests Results
+      if: always()
+      run: |
+        tests_status=${{ steps.mcp_venue_dev_integration_tests_with_ogc_api.outcome }}
+        echo "Tests Status: $tests_status"
+        if [ "$tests_status" != "success" ]; then
+          echo "Integration Tests with OGC API on MCP Venue Dev failed."
+          exit 1
+        fi
 
 #  Test-Venue-Airflow-API:
 #    runs-on: ubuntu-latest
@@ -107,14 +107,14 @@ jobs:
 #      id: mcp_venue_test_integration_tests_with_airflow_api
 #      continue-on-error: true
 #      env:
-#        AIRFLOW_WEBSERVER_PASSWORD: ${{ secrets.MCP_VENUE_TEST_AIRFLOW_WEBSERVER_PASSWORD }}
-#        UNITY_USER: ${{ secrets.UNITY_USER }}
-#        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+#        UNITY_USERNAME: ${{ secrets.MCP_VENUE_TEST_UNITY_USERNAME }}
+#        UNITY_PASSWORD: ${{ secrets.MCP_VENUE_TEST_UNITY_PASSWORD }}
+#        UNITY_CLIENTID: ${{ secrets.MCP_VENUE_TEST_UNITY_CLIENTID }}
 #      run: |
 #        pytest -vv -s --gherkin-terminal-reporter \
 #        unity-test/system/integration/step_defs/test_cwl_workflows_with_airflow_api.py \
 #        --venue="test" \
-#        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_ENDPOINT }} \
+#        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_API_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_API_ENDPOINT }} \
 #        --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT || vars.MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT }}
 #
 #    - name: Check Tests Results
@@ -142,14 +142,14 @@ jobs:
 #      id: mcp_venue_test_integration_tests_with_ogc_api
 #      continue-on-error: true
 #      env:
-#        AIRFLOW_WEBSERVER_PASSWORD: ${{ secrets.MCP_VENUE_TEST_AIRFLOW_WEBSERVER_PASSWORD }}
-#        UNITY_USER: ${{ secrets.UNITY_USER }}
-#        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+#        UNITY_USERNAME: ${{ secrets.MCP_VENUE_TEST_UNITY_USERNAME }}
+#        UNITY_PASSWORD: ${{ secrets.MCP_VENUE_TEST_UNITY_PASSWORD }}
+#        UNITY_CLIENTID: ${{ secrets.MCP_VENUE_TEST_UNITY_CLIENTID }}
 #      run: |
 #        pytest -vv -s --gherkin-terminal-reporter \
 #        unity-test/system/integration/step_defs/test_cwl_workflows_with_ogc_api.py \
 #        --venue="test" \
-#        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_ENDPOINT }} \
+#        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_API_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_API_ENDPOINT }} \
 #        --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT || vars.MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT }}
 #
 #    - name: Check Tests Results
