Running only SBG Preprocess on smaller machines

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -162,73 +162,73 @@ jobs:
           exit 1
         fi
 
-  Dev-Venue-SBG_Preprocess:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-
-    - name: Setup
-      uses: ./.github/actions/setup-action
-      continue-on-error: false
-
-    - name: MCP Venue Dev - SBG Preprocess
-      id: mcp_venue_dev_sbg_preprocess
-      continue-on-error: true
-      env:
-        AIRFLOW_WEBSERVER_PASSWORD: ${{ secrets.MCP_VENUE_DEV_AIRFLOW_WEBSERVER_PASSWORD }}
-        UNITY_USER: ${{ secrets.UNITY_USER }}
-        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
-      run: |
-        pytest -vv -s --gherkin-terminal-reporter \
-        unity-test/system/integration/step_defs/test_sbg_preprocess_workflow.py  \
-        --venue="dev" \
-        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_ENDPOINT }} \
-        --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT || vars.MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT }}
-
-    - name: Check Tests Results
-      if: always()
-      run: |
-        tests_status=${{ steps.mcp_venue_dev_sbg_preprocess.outcome }}
-        echo "Tests Status: $tests_status"
-        if [ "$tests_status" != "success" ]; then
-          echo "SBG Preprocess on MCP Venue Dev failed."
-          exit 1
-        fi
-
-
-  Test-Venue-SBG_Preprocess:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup
-        uses: ./.github/actions/setup-action
-        continue-on-error: false
-
-      - name: MCP Venue Test - SBG Preprocess
-        id: mcp_venue_test_sbg_preprocess
-        continue-on-error: true
-        env:
-          AIRFLOW_WEBSERVER_PASSWORD: ${{ secrets.MCP_VENUE_TEST_AIRFLOW_WEBSERVER_PASSWORD }}
-          UNITY_USER: ${{ secrets.UNITY_USER }}
-          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
-        run: |
-          pytest -vv -s --gherkin-terminal-reporter \
-          unity-test/system/integration/step_defs/test_sbg_preprocess_workflow.py  \
-          --venue="test" \
-          --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_ENDPOINT }} \
-          --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT || vars.MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT }}
-
-      - name: Check Tests Results
-        if: always()
-        run: |
-          tests_status=${{ steps.mcp_venue_test_sbg_preprocess.outcome }}
-          echo "Tests Status: $tests_status"
-          if [ "$tests_status" != "success" ]; then
-            echo "SBG Preprocess on MCP Venue Test failed."
-            exit 1
-          fi
+#  Dev-Venue-SBG_Preprocess:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#    - name: Checkout
+#      uses: actions/checkout@v4
+#
+#    - name: Setup
+#      uses: ./.github/actions/setup-action
+#      continue-on-error: false
+#
+#    - name: MCP Venue Dev - SBG Preprocess
+#      id: mcp_venue_dev_sbg_preprocess
+#      continue-on-error: true
+#      env:
+#        AIRFLOW_WEBSERVER_PASSWORD: ${{ secrets.MCP_VENUE_DEV_AIRFLOW_WEBSERVER_PASSWORD }}
+#        UNITY_USER: ${{ secrets.UNITY_USER }}
+#        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+#      run: |
+#        pytest -vv -s --gherkin-terminal-reporter \
+#        unity-test/system/integration/step_defs/test_sbg_preprocess_workflow.py  \
+#        --venue="dev" \
+#        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_ENDPOINT }} \
+#        --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT || vars.MCP_VENUE_DEV_OGC_PROCESSES_ENDPOINT }}
+#
+#    - name: Check Tests Results
+#      if: always()
+#      run: |
+#        tests_status=${{ steps.mcp_venue_dev_sbg_preprocess.outcome }}
+#        echo "Tests Status: $tests_status"
+#        if [ "$tests_status" != "success" ]; then
+#          echo "SBG Preprocess on MCP Venue Dev failed."
+#          exit 1
+#        fi
+#
+#
+#  Test-Venue-SBG_Preprocess:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v4
+#
+#      - name: Setup
+#        uses: ./.github/actions/setup-action
+#        continue-on-error: false
+#
+#      - name: MCP Venue Test - SBG Preprocess
+#        id: mcp_venue_test_sbg_preprocess
+#        continue-on-error: true
+#        env:
+#          AIRFLOW_WEBSERVER_PASSWORD: ${{ secrets.MCP_VENUE_TEST_AIRFLOW_WEBSERVER_PASSWORD }}
+#          UNITY_USER: ${{ secrets.UNITY_USER }}
+#          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+#        run: |
+#          pytest -vv -s --gherkin-terminal-reporter \
+#          unity-test/system/integration/step_defs/test_sbg_preprocess_workflow.py  \
+#          --venue="test" \
+#          --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_ENDPOINT }} \
+#          --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT || vars.MCP_VENUE_TEST_OGC_PROCESSES_ENDPOINT }}
+#
+#      - name: Check Tests Results
+#        if: always()
+#        run: |
+#          tests_status=${{ steps.mcp_venue_test_sbg_preprocess.outcome }}
+#          echo "Tests Status: $tests_status"
+#          if [ "$tests_status" != "success" ]; then
+#            echo "SBG Preprocess on MCP Venue Test failed."
+#            exit 1
+#          fi
