Testing OGC and Airflowmon venue dev

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -32,7 +32,6 @@ jobs:
 
   Dev-Venue-Airflow-API:
     runs-on: ubuntu-latest
-
     env:
       UNITY_USER: ${{ secrets.MCP_VENUE_DEV_UNITY_USERNAME }}
       UNITY_PASSWORD: ${{ secrets.MCP_VENUE_DEV_UNITY_PASSWORD }}
@@ -46,13 +45,6 @@ jobs:
         uses: ./.github/actions/setup-action
         continue-on-error: false
 
-      - name: MCP Venue Dev - Karpenter Integration tests with Airflow API
-        id: mcp_venue_dev_karpenter_integration_tests_with_airflow_api
-        continue-on-error: true
-        run: |
-          pytest -vv -s --gherkin-terminal-reporter \
-          unity-test/system/integration/step_defs/test_karpenter_test_workflow_with_airflow_api.py  \
-          --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_API_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_API_ENDPOINT }}
 
       - name: MCP Venue Dev - CWL Integration tests with Airflow API
         id: mcp_venue_dev_cwl_integration_tests_with_airflow_api
@@ -63,6 +55,14 @@ jobs:
           --venue="dev" \
           --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_API_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_API_ENDPOINT }} \
           --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_OGC_PROCESSES_API_ENDPOINT || vars.MCP_VENUE_DEV_OGC_PROCESSES_API_ENDPOINT }}
+
+      - name: MCP Venue Dev - Karpenter Integration tests with Airflow API
+        id: mcp_venue_dev_karpenter_integration_tests_with_airflow_api
+        continue-on-error: true
+        run: |
+          pytest -vv -s --gherkin-terminal-reporter \
+          unity-test/system/integration/step_defs/test_karpenter_test_workflow_with_airflow_api.py  \
+          --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_API_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_API_ENDPOINT }}
 
       - name: Check Tests Results
         if: always()
@@ -76,6 +76,55 @@ jobs:
           echo "Karpenter Tests Status: $karpenter_tests_status"
           if [ "$karpenter_tests_status" != "success" ]; then
             echo "Karpenter Integration Tests with Airflow API on MCP Venue Dev failed."
+          fi
+          if [ "$karpenter_tests_status" != "success" || "$cwl_tests_status" != "success" ]; then
+            exit 1
+          fi
+
+  Dev-Venue-OGC-API:
+    runs-on: ubuntu-latest
+    env:
+      UNITY_USER: ${{ secrets.MCP_VENUE_DEV_UNITY_USERNAME }}
+      UNITY_PASSWORD: ${{ secrets.MCP_VENUE_DEV_UNITY_PASSWORD }}
+      UNITY_CLIENT_ID: ${{ secrets.MCP_VENUE_DEV_UNITY_CLIENTID }}
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+
+    - name: Setup
+      uses: ./.github/actions/setup-action
+      continue-on-error: false
+
+    - name: MCP Venue Dev - CWL Integration tests with OGC API
+      id: mcp_venue_dev_cwl_integration_tests_with_ogc_api
+      continue-on-error: true
+      run: |
+        pytest -vv -s --gherkin-terminal-reporter \
+        unity-test/system/integration/step_defs/test_cwl_workflows_with_ogc_api.py \
+        --venue="dev" \
+        --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_OGC_PROCESSES_API_ENDPOINT || vars.MCP_VENUE_DEV_OGC_PROCESSES_API_ENDPOINT }}
+
+    - name: MCP Venue Dev - Karpenter Integration tests with OGC API
+      id: mcp_venue_dev_karpenter_integration_tests_with_ogc_api
+      continue-on-error: true
+      run: |
+        pytest -vv -s --gherkin-terminal-reporter \
+        unity-test/system/integration/step_defs/test_karpenter_test_workflow_with_ogc_api.py  \
+        --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_OGC_PROCESSES_API_ENDPOINT || vars.MCP_VENUE_DEV_OGC_PROCESSES_API_ENDPOINT }}
+
+    - name: Check Tests Results
+      if: always()
+      run: |
+          cwl_tests_status=${{ steps.mcp_venue_dev_cwl_integration_tests_with_ogc_api.outcome }}
+          echo "CWL Tests Status: $tests_status"
+          if [ "$cwl_tests_status" != "success" ]; then
+            echo "CWL Integration Tests with OGC API on MCP Venue Dev failed."
+          fi
+          karpenter_tests_status=${{ steps.mcp_venue_dev_karpenter_integration_tests_with_ogc_api.outcome }}
+          echo "Karpenter Tests Status: $karpenter_tests_status"
+          if [ "$karpenter_tests_status" != "success" ]; then
+            echo "Karpenter Integration Tests with OGC API on MCP Venue Dev failed."
           fi
           if [ "$karpenter_tests_status" != "success" || "$cwl_tests_status" != "success" ]; then
             exit 1
