Adding Ops venue to integration tests

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -21,7 +21,13 @@ on:
       MCP_VENUE_TEST_OGC_PROCESSES_API_ENDPOINT:
         description: "Base URL for the OGC endpoint in MCP Venue Test (i.e. https://abcdef12345.execute-api.us-west-2.amazonaws.com/test/ogc/api)"
         type: string
-      # TODO: add MCP_VENUE_OPS inputs
+      MCP_VENUE_OPS_AIRFLOW_API_ENDPOINT:
+        description: "Base URL for the Airflow API endpoint in MCP Venue Ops (i.e. https://abcdef12345.execute-api.us-west-2.amazonaws.com/test/sps/api/v1)"
+        type: string
+      MCP_VENUE_OPS_OGC_PROCESSES_API_ENDPOINT:
+        description: "Base URL for the OGC endpoint in MCP Venue Ops (i.e. https://abcdef12345.execute-api.us-west-2.amazonaws.com/test/ogc/api)"
+        type: string
+
 jobs:
 
   Dev-Venue-Airflow-API:
@@ -94,6 +100,41 @@ jobs:
           exit 1
         fi
 
+  Ops-Venue-Airflow-API:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup
+        uses: ./.github/actions/setup-action
+        continue-on-error: false
+
+      - name: MCP Venue Ops - Integration tests with Airflow API
+        id: mcp_venue_ops_integration_tests_with_airflow_api
+        continue-on-error: true
+        env:
+          UNITY_USER: ${{ secrets.MCP_VENUE_OPS_UNITY_USERNAME }}
+          UNITY_PASSWORD: ${{ secrets.MCP_VENUE_OPS_UNITY_PASSWORD }}
+          UNITY_CLIENT_ID: ${{ secrets.MCP_VENUE_OPS_UNITY_CLIENTID }}
+        run: |
+          pytest -vv -s --gherkin-terminal-reporter \
+          unity-test/system/integration/step_defs/test_cwl_workflows_with_airflow_api.py  \
+          --venue="prod" \
+          --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_OPS_AIRFLOW_API_ENDPOINT || vars.MCP_VENUE_OPS_AIRFLOW_API_ENDPOINT }} \
+          --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_OPS_OGC_PROCESSES_API_ENDPOINT || vars.MCP_VENUE_OPS_OGC_PROCESSES_API_ENDPOINT }}
+
+      - name: Check Tests Results
+        if: always()
+        run: |
+          tests_status=${{ steps.mcp_venue_ops_integration_tests_with_airflow_api.outcome }}
+          echo "Tests Status: $tests_status"
+          if [ "$tests_status" != "success" ]; then
+            echo "Integration Tests with Airflow API on MCP Venue Ops failed."
+            exit 1
+          fi
+
   Dev-Venue-OGC-API:
     runs-on: ubuntu-latest
 
@@ -163,3 +204,38 @@ jobs:
           echo "Integration Tests with OGC API on MCP Venue Test failed."
           exit 1
         fi
+
+  Ops-Venue-OGC-API:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup
+        uses: ./.github/actions/setup-action
+        continue-on-error: false
+
+      - name: MCP Venue Ops - Integration tests with OGC API
+        id: mcp_venue_ops_integration_tests_with_ogc_api
+        continue-on-error: true
+        env:
+          UNITY_USER: ${{ secrets.MCP_VENUE_OPS_UNITY_USERNAME }}
+          UNITY_PASSWORD: ${{ secrets.MCP_VENUE_OPS_UNITY_PASSWORD }}
+          UNITY_CLIENT_ID: ${{ secrets.MCP_VENUE_OPS_UNITY_CLIENTID }}
+        run: |
+          pytest -vv -s --gherkin-terminal-reporter \
+          unity-test/system/integration/step_defs/test_cwl_workflows_with_ogc_api.py \
+          --venue="prod" \
+          --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_OPS_AIRFLOW_API_ENDPOINT || vars.MCP_VENUE_OPS_AIRFLOW_API_ENDPOINT }} \
+          --ogc-processes-endpoint=${{ github.event.inputs.MCP_VENUE_OPS_OGC_PROCESSES_API_ENDPOINT || vars.MCP_VENUE_OPS_OGC_PROCESSES_API_ENDPOINT }}
+
+      - name: Check Tests Results
+        if: always()
+        run: |
+          tests_status=${{ steps.mcp_venue_ops_integration_tests_with_ogc_api.outcome }}
+          echo "Tests Status: $tests_status"
+          if [ "$tests_status" != "success" ]; then
+            echo "Integration Tests with OGC API on MCP Venue Ops failed."
+            exit 1
+          fi
