Adding back integration test for Test Venue

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -29,6 +29,14 @@ jobs:
         python -m pip install --upgrade pip
         pip install -e ".[test]"
 
+    - name: MCP Venue Test - Integration tests
+      id: mcp_venue_test_integration_tests
+      continue-on-error: true
+      run: |
+        pytest -vv --gherkin-terminal-reporter \
+        unity-test/system/integration \
+        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_ENDPOINT }}
+
     - name: MCP Venue Dev - Integration tests
       id: mcp_venue_dev_integration_tests
       continue-on-error: true
@@ -39,21 +47,13 @@ jobs:
         unity-test/system/integration \
         --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_ENDPOINT }}
 
-    # - name: MCP Venue Test - Integration tests
-    #   id: mcp_venue_test_integration_tests
-    #   continue-on-error: true
-    #   run: |
-    #     pytest -vv --gherkin-terminal-reporter \
-    #     unity-test/system/integration \
-    #     --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_ENDPOINT }}
-
     - name: Check Integration Tests Results
       if: always()
       run: |
         dev_status=${{ steps.mcp_venue_dev_integration_tests.outcome }}
-        # test_status=${{ steps.mcp_venue_test_integration_tests.outcome }}
-        echo "Dev Integration Tests: $dev_status"
-        # echo "Test Integration Tests: $test_status"
+        test_status=${{ steps.mcp_venue_test_integration_tests.outcome }}
+        echo "Dev Venue Integration Tests status: $dev_status"
+        echo "Test Venue Integration Tests status: $test_status"
 
         if [ "$dev_status" != "success" ]; then
           echo "MCP Venue Dev Integration Tests failed."
@@ -61,7 +61,7 @@ jobs:
         fi
 
         # Uncomment this block when MCP Venue Test Integration tests are re-enabled
-        # if [ "$test_status" != "success" ]; then
-        #   echo "MCP Venue Test Integration Tests failed."
-        #   exit 1
-        # fi
+        if [ "$test_status" != "success" ]; then
+          echo "MCP Venue Test Integration Tests failed."
+          exit 1
+        fi
